# enbeddings_tunnable_params.yaml

embedding_tune_config:
  sequence_embeddings:
    ESM:
      use: [true, false]
      dim:
        values: [32, 64, 128]
    ProtT5:
      use: [true, false]
      dim:
        values: [32, 64, 128]
    ProstT5:
      use: [true, false]
      dim:
        values: [32, 64, 128]

  go_embeddings:
    use: [true, false]
    autoencoded_go_embeddings:
      input_dim:
        values: [50, 100, 200, 500, 1000]
      emb_dim:
        values: [32, 64, 128]  # Autoencoded dimensions
        include_original: [true, false]  # If true, also includes input_dim as emb_dim
      aggregated_dim:
        strategies: ["mean_pooling", "padding"]
      go_categories:
        values: ["C_F", "C_F_P"]