# config/config_classifier.yaml

defaults:
  - _self_
  - config_process

classifier_definition:

  label_col: "class"

  features_col: ['c_max_mbl', 'f_max_mbl', 'p_max_mbl', 'seq_length']

  sequence_embeddings:
    {
      "ESM": {
        "use_autoencoder": False,
        "autoencoded_embeddings": True,
        "target_dim": 128
      },
      "ProtT5": {
        "use_autoencoder": False,
        "autoencoded_embeddings": True,
        "target_dim": 128
      },
      "ProstT5": {
        "use_autoencoder": False,
        "autoencoded_embeddings": True,
        "target_dim": 128
      }
    }

  go_embeddings:
    {
      "GeOKG": {
        "autoencoded_embeddings": True,
        "input_dim": 500,
        "emb_dim": 128,
        "aggregated_dim": 1280,
        "aggregation_strategy": "padding",
        "go_categories": "C_F"
      }
    }

  organism_discrimination_strategy:
    {
      "use_selected_organisms": null,
      "use_top_organisms": 4
    }