# config/config_process.yaml

defaults:
  - _self_
  - config_load  # Inherits loading config

metrics:
  columns: ["seq_length", "c_max_mbl", "f_max_mbl", "p_max_mbl"]
  nan_strategy: "fill_minus_one"  # Options: drop, fill_mean, fill_zero
  scaler_type: "standard"    # Options: standard, minmax
  trim_config:
    column: ["seq_length"]
    max: 2000
    min: -1

sequence_embedding_name: "ProtT5"

go:
  dim: 500
  pooling: "mean_pool"
  go_type: "C_F_P"
