# config/config_process.yaml

defaults:
  - _self_
  - config_load.yaml

features:
  to_process: 
    - aa_onehot
    - pseaac
    - svmprot
    - 3di_onehot
    - pse3di
    # - go_onehot
    # - protT5
    # - prostT5
    # - esm2
