# config/load_config.yaml

dataset:
  root_dir: "./datasets"
  unified_dataset:
    file: "merged_dataset.csv"
    id_col: "accession_code"
    label_col: "class"
    organism_col: "organism"
    sequence_col: "sequence"
    metrics_col: ['c_max_mbl', 'f_max_mbl', 'p_max_mbl', 'seq_length']

options:
  use_embeddings: true
  load_from_raw: true
  use_embeddings_ids_as_reference: true