# paths/autoencoded_seq_embeddings.yaml

autoencoded_seq_embeddings:
  folder_path: "./csv_embeddings/autoencoded_seq_embeddings"
  ESM:
    - dim: 32
      file_name: "ESM_embeddings_32dim.csv"
    - dim: 64
      file_name: "ESM_embeddings_64dim.csv"
    - dim: 128
      file_name: "ESM_embeddings_128dim.csv"
  ProtT5:
    - dim: 32
      file_name: "ProtT5_embeddings_32dim.csv"
    - dim: 64
      file_name: "ProtT5_embeddings_64dim.csv"
    - dim: 128
      file_name: "ProtT5_embeddings_128dim.csv"
  ProstT5:
    - dim: 32
      file_name: "ProstT5_embeddings_32dim.csv"
    - dim: 64
      file_name: "ProstT5_embeddings_64dim.csv"
    - dim: 128
      file_name: "ProstT5_embeddings_128dim.csv"