# paths/embedding_paths.yaml

embedding_sequence_paths:
  ESM:
    folder_path: "../DATASETS/embeddings/sequence_embeddings"
    file_name: "esm_embeddings.csv"
    dic_csv:
      id_col: "accession_code"
      emb_col: "esm_embedding"
      emb_col_type: "string"
  ProtT5:
    folder_path: "../DATASETS/embeddings/sequence_embeddings"
    file_name: "protT5_embeddings.csv"
    dic_csv:
      id_col: "accession_code"
      emb_col: "esm_embedding"
      emb_col_type: "string"
  ProstT5:
    folder_path: "../DATASETS/embeddings/sequence_embeddings"
    file_name: "prostT5_embeddings.csv"
    dic_csv:
      id_col: "accession_code"
      emb_col: "esm_embedding"
      emb_col_type: "string"