mlp:
  parameters:
    num_hidden_layers:
      min: 1
      max: 5
      distribution: int_uniform  # Number of hidden layers
    dropout_rate:
      min: 0.0
      max: 0.5
      distribution: uniform  # Dropout probability in each layer
    hidden_layers_mode:
      values: ["quadratic_increase", "custom"]
    custom_hidden_layers:
      values:
        - [512, 256, 128]
        - [1024, 512, 256, 128]
        - [2048, 1024, 512, 256, 128]
    activation_function:
      values: ["ReLU", "LeakyReLU", "ELU", "GELU"]  # Options for activation
    use_batch_norm:
      values: [True, False]  # Optional BatchNorm
    output_activation:
      values: [null, "Sigmoid", "Tanh"]  # Activation for output layer
    initialization:
      values: [null, "xavier", "kaiming", "normal"]  # Weight initialization methods

  base_line:
    num_hidden_layers: 3
    dropout_rate: 0.2
    hidden_layers_mode: "quadratic_increase"
    custom_hidden_layers: Null
    activation_function: "ReLU"
    use_batch_norm: True
    output_activation: null
    initialization: "xavier"