wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 20
input_dim:
  value: 200
latent_dim:
  value: 32
learning_rate:
  value: 0.0008867419860092622
optimizer:
  value: Adam
