wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 50
input_dim:
  value: 200
latent_dim:
  value: 64
learning_rate:
  value: 0.003968092334066947
optimizer:
  value: SGD
